apiVersion: v1
kind: Service
metadata:
  name: auth-service-ms-service
  namespace: auth-service-ms-namespace
spec:
  selector:
    app: auth-deployment
  ports:
    - protocol: "TCP"
      port: 9199
      targetPort: 9199
  type: NodePort